### ISSUE TITLE
UNMET PEER DEPENDENCY sassdoc@^2.1.20

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/sassdoc-theme-herman#103]
I guess [this Susy issue](https://github.com/oddbird/susy/issues/634) should be here, instead.

```
sassdoc-theme-herman@0.5.5 requires a peer of sassdoc@^2.1.20 but none was installed.
```

**Comment by jgerigmeyer** [comment]
No, this only belongs on Susy (https://github.com/oddbird/susy/issues/634). If Susy relies on `sassdoc-theme-herman` as a dependency, it should also include `sassdoc` as a dependency.

**Comment by robsonsobral** [comment]
@jgerigmeyer , I installed `sassdoc-theme-herman` without susy and found this issue, too. This is the reason I reported it again.

**Comment by jgerigmeyer** [comment]
@robsonsobral Maybe I'm misunderstanding. `sassdoc-theme-herman` requires `sassdoc` as a `peerDependency` (not a regular `dependency`), which means it up to the consuming app/package to declare `sassdoc` as a dependency as well as `sassdoc-theme-herman` (see https://docs.npmjs.com/files/package.json#peerdependencies). So if you're seeing that warning, it means that you likely have not required `sassdoc` as a dependency for your project. Does that make sense?
