### ISSUE TITLE
ID attrs have invalid and inconsistent characters.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#106]
Some IDs are using spaces ` `, while others are encoded using `%20`. Internal hash links are broken.

TODO:
- [x] all `id` attr contents should be safe; only valid chars

**Comment by davisagli** [comment]
Can you be more specific about where this is happening?

**Comment by jgerigmeyer** [comment]
@davisagli There are two related issues I'm concerned about:

1) Inconsistent (broken) links. For instance, on the `code` page, the links to the `Code Blocks` section have `href="code.html#css--Code Blocks"`, which is both invalid HTML and also doesn't match the section `id="css--Code%20Blocks"`. The difference is between the `id` var set in `item/_item.j2` and the url created by the `get_link` macro in `item/macros.j2`, used in `item/annotation.macros.j2`.

2) Invalid characters in `id` attributes. Even in HTML5, `id` attributes should not contain whitespace, and must begin with a letter (or at least that's my understanding). If we're using dynamic content to generate `id` attributes, I want to be sure we're following the spec.

**Comment by jgerigmeyer** [comment]
Item #1 is fixed and PR is ready for review: https://github.com/oddbird/sassdoc-theme-herman/pull/171.

Re item #2, I reviewed all `id` attributes, and they are already valid.
