### ISSUE TITLE
Allow multiple markdown files, not just the index

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#117]
PR: #180 

It would be great to add `contributing`, `changelog`, etc

**Comment by jgerigmeyer** [comment]
Proposal:

- Add new herman-specific option (opt name?), array of objects each with `name` and `path` keys, e.g. `[{ name: 'Changelog', path: './CHANGELOG.md' }]`.
- OR... array of strings, interpreted as paths, and the filename becomes the `name`.
- These files are parsed as markdown and appended or prepended to the side-navigation.
