### ISSUE TITLE
Nav list-items aren't in lists

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#132]
![Screenshot](https://dl.dropbox.com/s/z4ioweat4bljwck/Screenshot%202017-06-15%2010.30.17.jpg)

Either add `ul` wrapper, or change `li`

**Comment by davisagli** [comment]
@mirisuzanne I added `ul` in the `nav-ul` branch, but I'm not sure if we want the margin that that adds...
