### ISSUE TITLE
Struggling to get examples working 

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/sassdoc-theme-herman#142]
This is more of a question, as I've tried to sift through the docs to get the previews of code working.  I've added the `Herman.sass` configuration as such:

```javascript
.pipe(sassdoc({
    dest: pkg.config.dirs.temp,
    exclude: [pkg.config.files.test],
    theme: 'herman',
    shortcutIcon: 'docs/assets/img/logo.png',
    herman: {
        sass: {
            includepaths: ['src']
        }
    }
}))
```

But I'm getting errors like this:

```shell
» [WARNING] Error compiling @example scss:
no mixin named timing

Backtrace:
	stdin:2
.animation-in {
  @include timing();
}
```

The place where this SCSS lives does not have any `sassdoc` within it and its just a normal CSS declaration.  What am I doing wrong?

**Comment by mirisuzanne** [comment]
@chrisopedia I think SassDoc compiles the entire file as Sass, not just the documented objects – so the mixin will have to be available/imported for that to work.
