### ISSUE TITLE
Make sure CSS exports make sense without Accoutrement

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#143]

**Comment by mirisuzanne** [comment]
@jgerigmeyer this is the issue I'm working on.

Currently Sass compiles three versions of every color, passing all three to the JSON export:

```json
{
  "brand-colors": {
    "brand-orange": {
      "output": "#c75000", 
      "rgba": "rgba(199, 80, 0, 1)", 
      "hsla": "hsla(24deg, 100%, 39%, 1)"
    },
    "etc": {"…"}
  }
}
```

This would be a much simpler API on the Sass end if we could pass in a single value in any format (hex, rgba, hsla) and have Herman compile the others for display. The JSON would look like this instead:

```json
{
  "brand-colors": {
    "brand-orange": "#c75000",
    "etc": "…"
  }
}
```

Maybe a tool like [TinyColor](https://bgrins.github.io/TinyColor/) could do the conversions?

**Comment by jgerigmeyer** [comment]
@mirisuzanne Makes sense. Herman also compiles sass (for the `@example` annotation), so if we want it seems possible we could just have Herman do that with node-sass instead of using a JS package.

**Comment by mirisuzanne** [comment]
@jgerigmeyer oh cool - anything I can do to help make that happen, or is this over to you?

**Comment by mirisuzanne** [comment]
@jgerigmeyer This is ready for a color-conversion filter (or filters).

- The input color will usually be hex, but sometimes rgba
- I think we only need conversion to hsl/a at this point

**Comment by jgerigmeyer** [comment]
Assigned to @davisagli and @stacyk for review of #145.
