### ISSUE TITLE
Remove Sass `_herman-inspect` function

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#151]
This JSON-validation should happen in https://github.com/oddbird/sass-json-export

Removing the sass utility relies on:
- https://github.com/oddbird/sass-json-export/issues/1
- https://github.com/oddbird/sass-json-export/issues/2

**Comment by mirisuzanne** [comment]
This should also allow us to remove `_herman-string-replace`

**Comment by jgerigmeyer** [comment]
@mirisuzanne What is the relevance of this now that we're no longer using `sass-json-export`?

**Comment by mirisuzanne** [comment]
This was fixed by that merger. Closing.
