### ISSUE TITLE
Add Herman/OddBird links to output

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#154]
Shouldn't be prominent, but this is one of the few tools we can put our stamp on without bothering anyone.

**Comment by wlonk** [comment]
Just a link in the footer-ish area that links to Herman docs, and to us.

**Comment by SondraE** [comment]
The OddBird link goes to the home page of OddSite.
The Herman link goes to oddbird.net/herman.

![screen shot 2017-11-14 at 11 45 33 am](https://user-images.githubusercontent.com/8933115/32798267-68bbb290-c931-11e7-863b-4f3a559684eb.png)
