### ISSUE TITLE
Herman logo and favicon‽

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#155]
If we want to keep things simple, we could try to follow the Susy logo pattern? Or maybe we have a better idea?

**Comment by jgerigmeyer** [comment]
Do we just want to use the logo currently on OddSite? (Can we get a favicon as well?)

**Comment by SondraE** [comment]
I like the logo that's similar to the Susy "S". 

The only change I think may be nice would be a different color. Here are a couple options that look nice with the Susy pink and the OddBird brand colors. (Both pass WCAG AA for small text too.)
- Purple #6F05AA
- Red #C41B00

@mirisuzanne I went ahead and made a favicon of the Herman logo. ([See Dropbox](https://www.dropbox.com/home/OddBird%20(2)/active%20projects/Herman?preview=logo.svg))
