### ISSUE TITLE
I want to publically release 1.0

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#163]
What's the message, how do we frame it, where do we publicize, does it tie in with services, etc?

**Comment by SondraE** [comment]
@mirisuzanne Here's my first draft of a publicity plan for Herman. Publicity options need prioritizing, and there are several questions for you and @stacyk.
I'd like to run our plans and messaging by Brad at our next Cultivate meeting on Nov 16th. 
Messaging needs more thought. Perhaps a Hangout chat with the 3 of us as you two have a better handle on how Herman benefits developers and business owners.
https://docs.google.com/document/d/1bKwnZRNMGhyj_NsAM_nTC6IJaHl3ayLCvxTr_eB_VV0/edit#

**Comment by SondraE** [comment]
@mirisuzanne @stacyk 
Publicity plan for Herman documented and prioritized as stories in OddSite and OddMarketing. 
Assigned these stories to the 3 of us. Perhaps a conversation after standup to check priorities is in order.
