### ISSUE TITLE
Replace "subprojects" option with simpler external links.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#175]
## `@example`, `@font`, `@icons` annotations don't work in subprojects?

I need to test this to be sure, but my hunch is that `basePath` is not accessible in the `iframe` templates, so when the subprojects are compiled they are not pointing to the correct path for `customCSS` and Herman styles.

**Comment by mirisuzanne** [comment]
In our process, it's unlikely for a subproject to have rendered examples. I'm not sure how true that would be across-the-board, but it's a feature I'd be comfortable putting off for now.

**Comment by jgerigmeyer** [comment]
Sure, I'm fine putting off a fix. I just think the entire `subprojects` thing is pretty fragile, so I'd like to document it as an alpha feature until we revisit.

**Comment by jgerigmeyer** [comment]
Proposal: Instead of including nested documentation for subprojects (which requires them having Herman setup as well), just allow an arbitrary list of external links to display in the sidebar nav.
