### ISSUE TITLE
iFrame sizing causes internal scroll with margins?

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#176]
Add margins to a rendered example, and the iframe will get a scroll-bar rather than resizing to include the margins.

**Comment by mirisuzanne** [comment]
@jgerigmeyer I don't think this should be assigned to me. It has to do with the JS iframe-sizing.

**Comment by jgerigmeyer** [comment]
@mirisuzanne Okay, then I just need more info about what's happening. Show me a broken case?

**Comment by jgerigmeyer** [comment]
@mirisuzanne Nevermind, I think I figured it out. Fixed.
