### ISSUE TITLE
Icons layout is broken.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#178]
![screenshot 2017-10-30 12 27 37](https://user-images.githubusercontent.com/552316/32182853-11909b58-bd6e-11e7-8637-5763ed63cf00.jpg)

**Comment by stacyk** [comment]
PR #192

**Comment by stacyk** [comment]
Its getting better, and this screenshot is outdated, but the issue I am having is the breaking if a long name on the right column. I want to force break the text at `/` but there isn't a CSS way to do so TMK.
![screen shot 2017-11-16 at 2 24 23 pm](https://user-images.githubusercontent.com/1581694/32915481-a099cf54-cade-11e7-9725-36d8a669e5df.jpg)

**Comment by stacyk** [comment]
![screen shot 2017-11-16 at 4 15 41 pm](https://user-images.githubusercontent.com/1581694/32918896-85f04010-cae9-11e7-8889-7fdc9734ee24.jpg)
