### ISSUE TITLE
Deprecate @macro annotation?

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#182]
Currently, the `@macro` annotation doesn't do anything, because we're not displaying it in the Herman templates. Everywhere we used to use it we've replaced it with `@example njk`. Is there any reason to keep `@macro` around? I guess it's currently the only way to document within a nunjucks file... If we don't deprecate it, we should make sure it displays in the compiled docs.

**Comment by mirisuzanne** [comment]
Yes, it should be deprecated in favor of #21
