### ISSUE TITLE
Remove HTML minifier?

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#186]
How much do we really gain from minifying the compiled HTML files? Is that level of performance increase important for a styleguide?

Only reason to remove it would be to make diffs much more readable.

**Comment by jgerigmeyer** [comment]
@mirisuzanne @wlonk @davisagli What do y'all think about this? I'd find it helpful for development, and probably also for users who check in their docs (e.g. OddSite).

**Comment by mirisuzanne** [comment]
I agree. People could add a minification step in their own build process if they really need it, right?
