### ISSUE TITLE
Async annotations do not work.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#199]
See https://github.com/SassDoc/sassdoc/issues/517, and PR https://github.com/SassDoc/sassdoc/pull/518.

**Comment by jgerigmeyer** [comment]
A couple things to note:

1) Until this gets fixed, compiled iframes may disappear seemingly at random (race conditions). So don't freak out if you see that.
2) If my PR doesn't get merged into SassDoc before we want to release 1.0, we _could_ re-write our annotations to be sync instead of async. It wouldn't really hurt, except there's otherwise no good reason to do it.

**Comment by pascalduez** [comment]
`sassdoc@2.5.0` thanks!

**Comment by jgerigmeyer** [comment]
Fixed by https://github.com/oddbird/sassdoc-theme-herman/commit/3b6ad69cbe149fd0d044934b77ac86daf9e23d94.
