### ISSUE TITLE
`@preview` is no longer universal. Should it be removed?

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#206]
When we first built it, all previews used the `@preview` syntax. Now only colors & sizes/ratios continue to use that prefix, while `@font` and `@icons` get their own annotation. Is there a reason to hold onto the shared syntax at all, rather than using e.g. `@colors`, `@sizes`, and `@ratios`?

**Comment by wlonk** [comment]
See https://github.com/oddbird/sassdoc-theme-herman/pull/208
