### ISSUE TITLE
readme links in the Herman Annotations section are broken

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#211]
https://github.com/oddbird/sassdoc-theme-herman#herman-annotations

They go to 404 on OddBird.

**Comment by jgerigmeyer** [comment]
This is true for most of the links in the Herman docs, which point to oddbird.net/herman/docs. They will be fixed when we upgrade Herman on OddSite and deploy it, which I plan to do at the next RC version bump.

**Comment by jgerigmeyer** [comment]
@stacyk Should be fixed now.
