### ISSUE TITLE
Allow nested `///` in SassDoc comments.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#212]
When we want to document how to document something, ideally we could do:

```scss
/// /// @colors
```

But SassDoc strips both sets of `///`, leaving just `@colors` instead of `/// @colors`. Right now we're using a workaround -- `/// // @colors`, which results in `// @colors` -- but that's a bit confusing. Can we submit a PR to SassDoc to make this work?

**Comment by jgerigmeyer** [comment]
I explored this a bit today. It stems from CDocParser, which automatically strips any occurrence of `///` from the comments. I'm not sure what the best solution is... Ideally we could enforce only one comment per line, so that only one occurrence of `///` is stripped per line.

Issues filed in [CDocParser](https://github.com/FWeinb/CDocParser/issues/16) and [SassDoc](https://github.com/SassDoc/sassdoc/issues/519).

**Comment by mirisuzanne** [comment]
The related question I got while showing this around was: "can I use a block-comment format, rather than line-comments?" That would likely have to be some marked variant on CSS comment style. Maybe with extra `*`? I assume that would be a new story, but is it even feasible using SassDoc? 

```scss
/***
  Some way to have comment blocks
  without marking every line?
  @group api
***/
```

**Comment by jgerigmeyer** [comment]
I'm pretty sure SassDoc used to support that, but intentionally dropped it: https://github.com/SassDoc/sassdoc/issues/326#issuecomment-213119230

**Comment by mirisuzanne** [comment]
Yeah, that's partly because they only support Sass. We also support CSS for the basic features, making it a more reasonable option for us. But if we'd have to go through them, likely an issue.

**Comment by jgerigmeyer** [comment]
If we fork SassDoc we could pretty easily enable block comments, and see if it breaks anything else. https://github.com/SassDoc/sassdoc/issues/467

**Comment by jgerigmeyer** [comment]
I submitted a PR to CDocParser that seems to fix this (https://github.com/FWeinb/CDocParser/pull/17), and opened a new Herman PR using that fork (#220).
