### ISSUE TITLE
`herman-export` includes incorrectly escaped quotes in Ruby Sass

### ISSUE THREAD

**Issue by chrisfromredfin** [oddbird/sassdoc-theme-herman#236]
I am very possibly doing something wrong, but I'm officially stuck. :)

Here's what I've done:

- set up `jsonfile: 'exported.json'` in my .sassdocrc
- ran 'sass ./sass/style.scss > exported.json' (my exported.json looks like `/*! json-encode: {"\"colors\"": {"\"demo-colors\"": {"\"brand-blue\"": "#0d7fa5", "\"brand-pink\"": "#e2127a"}}} */`
- ran `node_modules/sassdoc/bin/sassdoc sass`
- my style.scss has the $demo-colors map, the $brand-colors variables (all taken from the docs), a herman-add() call at the bottom, and a herman-export at the bottom.

```
// Colors
/// @colors

$brand-blue: hsl(195, 85%, 35%);
$brand-pink: hsl(330, 85%, 48%);
$demo-colors: (
  'brand-blue': $brand-blue,
  'brand-pink': $brand-pink,
);

// Add stuff to the $herman map.
@include herman-add('colors', 'demo-colors', $demo-colors);

@include herman-export;
```

The error I receive is:

```
Unhandled rejection Template render error: (unknown path)
  Template render error: (/redfin/www/hermanblog.rfslocal.site/node_modules/sassdoc-theme-herman/templates/item/_item.njk)
  Template render error: list filter: type not iterable
    at Object.exports.prettifyError (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/lib.js:34:15)
    at /redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:486:31
    at eval (eval at _compile (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:74:12)
    at eval (eval at _compile (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:119:12)
    at /redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:494:25
    at eval (eval at _compile (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:35:12)
    at /redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:538:16
    at new_cls.root [as rootRenderFunc] (eval at _compile (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:355:3)
    at new_cls.getExported (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:532:14)
    at eval (eval at _compile (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:34:6)
    at createTemplate (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:249:25)
    at /redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:263:21
    at next (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/redfin/www/hermanblog.rfslocal.site/node_modules/nunjucks/src/environment.js:242:17)
```

I am trying to write a "getting started with Herman" blog post, but so far, no luck getting into the real guts of what makes Herman awesome, i.e. `@colors` and `@fonts` annotations, etc. I think there's some missing link. It took me quite a while to find in the docs that the herman.sass.jsonfile was required, and I think I've generated it correctly, but I'm stuck at Nunjucks here, since these are the templates that come with the project.

**Comment by jgerigmeyer** [comment]
@chrisfromredfin Glad you're working on the blog post, and apologies that the error messages are not more helpful! I'm slowly working toward making them more useful, and reports like this make that possible.

In this case the issue is the empty line between your annotation (`/// @colors`) and the block being documented (`$brand-blue:...`). While SassDoc allows empty newlines between the documentation and the documented Sass code, Herman does not. Instead, Herman interprets the documentation as free-floating "prose", unattached to any Sass code. See http://oddbird.net/herman/docs/index.html#sassdoc-comments, although it's not very thorough in noting that point.

So basically, in your case the `@colors` annotation is not attached to any code, so it doesn't know which color Sass map you're trying to display. You can fix this in one of two ways:

1) Add a `key` argument to your `@colors` annotation (see http://oddbird.net/herman/docs/demo_colors.html#preview-color-maps-as-palettes), telling it which map you're displaying: `/// @colors demo-colors`

2) Remove the newline, and make sure the `$demo-colors` map is the _first_ newline following the documentation block. When you don't pass a `key` argument to `@colors`, it uses the variable name being documented.

Hopefully that helps! It's not deployed yet, but I've added some documentation clarifying this, and also added a more helpful warning (instead of the Nunjucks error) when a custom annotation (`@colors`, `@font`, `@ratios`, or `@sizes`) is used in a free-floating "prose" block without a `key` argument: https://github.com/oddbird/sassdoc-theme-herman/commit/77eaa05c41a53ec07eabe2d6699fc04a83c18f51

Please let us know if you run into further issues! We'll continue making improvements, and fleshing out the docs to be clearer and more useful.

(By the way, your Sass JSON file looks great -- we're currently working on making that entire process more seamless and easier to setup [#217], or at least better documented [#216]...)

**Comment by chrisfromredfin** [comment]
Sadly, that's not it, actually. I tried with demo-colors, without, etc. Here's my entire style.scss file (I'm not using any partials for the time being to work with the simplest possible setup), including your feedback. I have the same error here. 

```
// Import Herman utilities so we can access the various and sundry utilities.
@import "../node_modules/sassdoc-theme-herman/scss/utilities";


// ==========

/// Components: small, re-useable components used on the site.
/// @group components

/// @name Button
/// @group Components
/// @example markup
///   <a href="#" class="button">Click me</a>
%button {
  border-radius: 5px;
  background-color: green;
  color: white;
  font-weight: bold;
}

/// Mixins: custom re-useable but configurable tools we use.
/// @group Mixins

/// Helper mixin to drop on the wrapper for an iframe
/// that you would like to be responsive.
///
/// @group Mixins
/// @author Smashing Magazine
///
/// @param {Length} $width - Element's width
/// @param {Length} $height - Element's height
/// @output CSS for the wrapper and the inner iframe that maintains the aspect
///   ratio as it is resized.
///
/// @example scss -
///   @import "style.scss";
///   .embed-container {
///     @include embed-container(400px, 300px);
///   }
@mixin embed-container($width, $height) {
  $ratio: ($height / $width) * 100%;
  position: relative;
  padding-bottom: $ratio;
  height: 0;
  overflow: hidden;
  max-width: 100%;
  iframe, object, embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}

/// @group icons
/// @icons svg/



// @font lato (regular)
//   <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
// @example
// %sans {
//   font-family: Lato, Arial, sans-serif;
// }
// $lato: (
//   'name': 'Lato',
//   'source': "https://fonts.google.com/specimen/Lato",
//   'stack': (Arial, sans-serif),
// );

// Colors
$brand-blue: hsl(195, 85%, 35%);
$brand-pink: hsl(330, 85%, 48%);

/// @colors demo-colors
$demo-colors: (
  'brand-blue': $brand-blue,
  'brand-pink': $brand-pink,
);


// ==========
// Add stuff to the $herman map.

@include herman-add('colors', 'demo-colors', $demo-colors);

// @include herman-add('font', 'lato', $lato);

@include herman-export;
```

**Comment by jgerigmeyer** [comment]
@chrisfromredfin Oops; thanks for providing more info. From looking closer at the `exported.json` you posted above, it does look like there's a bug in how `herman-export` is treating quotes. You said your Sass JSON is:

```css
/*! json-encode: {"\"colors\"": {"\"demo-colors\"": {"\"brand-blue\"": "#0d7fa5", "\"brand-pink\"": "#e2127a"}}} */
```

It should be:

```css
/*! json-encode: {"colors": {"demo-colors": {"brand-blue": "#0d7fa5", "brand-pink": "#e2127a"}}} */
```

Not sure why it's adding in all those escaped quotes for Sass map keys, but that does appear to be the issue. @mirisuzanne is looking into it.

What's weird is that when I run the exact same commands, with the exact same file you pasted above, I get `exported.json`:

```css
/*! json-encode: {"colors": {"demo-colors": {"brand-blue": "#0d7fa5", "brand-pink": "#e2127a"}}} */
```

So I can't figure out why my output doesn't match yours. What versions of `node-sass` and `sassdoc-theme-herman` are you using? I'm on:

```bash
sassdoc-theme-herman@1.0.1
node-sass	4.7.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

**Comment by chrisfromredfin** [comment]
Aha, getting somewhere. Yarn shows me the following:

```
$> yarn list --pattern sass
yarn list v1.3.2
├─ node-sass@4.7.2
├─ sass-convert@0.5.2
├─ sass-graph@2.2.4
├─ sassdoc-extras@2.4.2
├─ sassdoc-theme-default@2.6.1
├─ sassdoc-theme-herman@1.0.1
└─ sassdoc@2.5.0
Done in 1.18s.
$> sass -v
Sass 3.4.25 (Selective Steve)
```

I do not have libsass anywhere in the yarn packages. I am using the regular Ruby Sass (globally installed) to compile the json. I'm guessing maybe that could be the difference.

**Comment by jgerigmeyer** [comment]
Ah, interesting. Do you get different results if you run `./node_modules/.bin/node-sass ./sass/style.scss > exported.json` instead?

**Comment by chrisfromredfin** [comment]
YES. In fact, it makes the entire thing suddenly work. :) I have been seriously put like 12 hours of head-scratching into this. I have to say where I've been burned has been in stripping it down to its essentials, when in fact most of the testing and use of this has been in a modern stack. 

(The other thing that burned me is that I tried to selectively comment things out. In this way, the sassdoc parser was still reading the triple-slash comments and trying to compile them, but all the maps it needed were not there; I THINK those were the nunjucks "item not iterable" errors.. or at least sometimes they were.)

So perhaps an issue to look at how to deal with Ruby Sass complications? Not sure if the right thing is to require node-sass, or detect ruby sass encoding and deal with it, or... ?

**Comment by jgerigmeyer** [comment]
Thanks, that's helpful feedback. It's true that our testing has primarily been with a modern stack, and entirely with node-sass. I don't really like the idea of just not supporting Ruby Sass...

Here's the full test in SassMeister, where you can see the differences between Libsass and Ruby Sass: https://www.sassmeister.com/gist/f911192e73082c7a6368a0d73e9973a5

**Comment by jgerigmeyer** [comment]
...and just like that, @mirisuzanne comes along with a PR that appears to fix the issue in Ruby Sass! 🎉 

I'll try to get a patch release out today. Thanks again for reporting -- please let us know any further bugs or just generally confusing things you run into!

**Comment by mirisuzanne** [comment]
@jgerigmeyer We should get our tests running in Ruby - there is almost always a good way to support both. Is that something we can setup with our CI tools?

**Comment by jgerigmeyer** [comment]
@chrisfromredfin I've released `v1.1.0`, which should fix the Ruby Sass bug.

**Comment by chrisfromredfin** [comment]
I wanted to come back and say that I tried this with dart-sass as well, and like ruby sass it outputs the encodings in the json - so a good future-forward fix as well (and, of course, thanks!).

**Comment by chrisfromredfin** [comment]
I know it's bad to touch closed issues, but I wanted to follow up because I FINALLY POSTED MY BLOG POST. :)

https://redfinsolutions.com/blog/getting-started-herman-living-style-guides-and-pattern-libraries

Feel free to leave comments!
