### ISSUE TITLE
Cleaner way to document available arguments for a macro 

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#24]
Showing an element's visual appearance on the front end in the styleguide currently is done by using importing the macro and including the code you'd use within a template to display the element.

for example:

```
/// @group Buttons
/// @example njk -
///   {% import 'buttons.macros.njk' as btn %}
///   {{ btn.button( color='none', content='medium with icon', size='medium', icon='x', loader='loading' ) }}
```

In my opinion, having a list of all possible arguments clearly listed, in a simple to read format on the styleguide would be incredibly helpful when building out templates. Something that would compile to:

| Property Name | Required? | Default |
| --- | --- | --- |
| color | --- | 'go' or `#008000` (show an inline swatch like Slack  😄) |
| content | yes | --- |
| icon | --- | --- |
| id | yes | --- |
| loader | --- | --- |
| size | --- | 'medium' |

This is especially true if there are multiple people on a project, if a new person comes in mid-project, handing this over to the client or another team upon completion, or even revisiting this project after some time has passed.

Furthermore, it would be great to find a way to grab the list of required and optional arguments along with their defaults (if they exist) from the macro itself instead of re-documenting it in the scss files. This would lessen the chance of it becoming outdated and help keep the scss documents less bloated (for ease of skimming/maintenance, not performance).

**Comment by mirisuzanne** [comment]
This is a duplicate, though it may contain relevant context for #21
