### ISSUE TITLE
[WARNING] Theme `/herman` not found.

### ISSUE THREAD

**Issue by adamwright104** [oddbird/sassdoc-theme-herman#251]
running sassdoc styles.scss --theme herman doesn't pick up the theme

**Comment by jgerigmeyer** [comment]
Do you have `sassdoc-theme-herman` installed and available in `node_modules/`? Can you post the contents of your `styles.scss` file?

**Comment by Truemedia** [comment]
I'm having this issue now aswell. I check and both sassdoc and sassdoc-theme-herman are in my node _modules.

This is the console output (using both command suggested in docs, and experimenting with setting in config):
```bash
» [WARNING] Theme `herman` not found.
» [WARNING] Falling back to default theme.
» [WARNING] Parser for annotation `flag` not found. Location: `linePoster.test.scss:5:8`
```

**Comment by jgerigmeyer** [comment]
@Truemedia Could you post your config file, or even better link to a sample repo that demonstrates the error? Thanks!

**Comment by jgerigmeyer** [comment]
To be clear, each top level folder is a git repo, but there's also a top level `node_modules` folder with `sassdoc` and `sassdoc-theme-herman` installed? e.g.

```
- node_modules/
  - sassdoc/
  - sassdoc-theme-herman/
- repo-one/
  - src/
    - foo.scss
- repo-two/
  - src/
    - bar.scss
```

**Comment by jgerigmeyer** [comment]
This sounds like a bug with sassdoc itself, in that case. I'm not sure how themes are resolved, but I'm happy to play with it if you can push a sample repo where it's not working.

**Comment by laras126** [comment]
@jgerigmeyer I'm having a similar issue – here is a test repo: https://github.com/laras126/herman-test

To replicate the issue:

1. Clone the repo and `npm install` 
2. Run `sassdoc utils --theme herman` inside herman-test/
3. See error: 
```
➜  herman-test git:(master) sassdoc utils --theme herman
» [WARNING] Theme `herman` not found.
» [WARNING] Falling back to default theme.
```

**Comment by jgerigmeyer** [comment]
@laras126 I'm guessing you have `sassdoc` installed globally, the CLI is using that version instead of the repo-specific version, and therefore it's looking for `sassdoc-theme-herman` installed globally as well.

On your sample repo, it works as expected if I run:

```sh
./node_modules/.bin/sassdoc utils --theme herman
```

You could also run it via an npm script, since that automatically uses repo-specific packages first:

```json
  "scripts": {
    "sassdoc": "sassdoc utils --theme herman"
  },
```

```sh
npm run sassdoc
```
