### ISSUE TITLE
Multiline comments appear in @example (should be removed?)

### ISSUE THREAD

**Issue by darbymanning** [oddbird/sassdoc-theme-herman#263]
I have a lot of partials in my project for numerous mixins - and these mixins contain multiline comments. Because of this, using `@example` to output the generated css for an individual mixin also displays these multiline comments from all of the other partials. Is there a way I can compile sass with the `compressed` output style so that these comments are not preserved?

I wasn't sure if this was an issue to do with sassdoc itself, but based on their describing of this issue [here](http://sassdoc.com/frequently-asked-questions/#why-does-the-logo-show-a-type-of-comment-that-is-not-supported) I suspect this may be something herman specific.

**Comment by jgerigmeyer** [comment]
Thanks for reporting! Could you provide a simple example or test case?

**Comment by deap82** [comment]
Using the compressed output style does remove the multiline comments, but also makes the compiled css quite hard to read.

For now I'll probably try the trick mentioned here, to style away the comments;
https://github.com/oddbird/sassdoc-theme-herman/issues/252#issuecomment-361395093

Herman is awesome though! A lot better than the sassdoc standard template, which almost made me abandon sassdoc before finding this.
