### ISSUE TITLE
customCSS url() rewriting is broken on Windows

### ISSUE THREAD

**Issue by rjgotten** [oddbird/sassdoc-theme-herman#265]
URLs in `customCSS` that are rewritten, end up broken on Windows. The rewriting logic uses the `path` module, which uses `\` as the separator on Windows and you end up with broken URLs.

**Comment by jgerigmeyer** [comment]
Thanks! A PR (with tests) would be welcome; otherwise I'll try to get to this in the next week.

**Comment by jgerigmeyer** [comment]
@rjgotten We're now running tests against a Windows environment, but I don't have a good way to functionally check that this is working in Windows. Would you be willing to try against the `master` branch and see if this is adequately fixed? Thanks!

**Comment by rjgotten** [comment]
@jgerigmeyer 
This seems to be working OK now. 
The paths are correctly rewritten.
