### ISSUE TITLE
customCSS URL rewriting exemption-check is broken

### ISSUE THREAD

**Issue by rjgotten** [oddbird/sassdoc-theme-herman#266]
URLs rewritten inside `customCSS` have an exemption list, but it is incomplete and in part broken.

Current exemption logic is:
```js
if (
  !src_path.startsWith('http') &&
  !src_path.startsWith('//') &&
  !src_path.startsWith('data:')
) {
  // ...
}
```

This has two problems:
- It fails to rewrite relative urls such as `url("http_foo/bar.jpg")` which are most definitely relative, because the starting check for HTTP is overly naive.
- It mistakingly rewrites domain-relative paths such as `url("/foo/bar.jpg")`, because it fails to detect them outright.

You can cover all the necessary cases with a simple regex, afaict:
```js
let regNoRewrite = /^(?:https?\:|data\:|\/)/i;
if ( !regNoRewrite.test(src_path)) {
  // ...
}
```

**Comment by jgerigmeyer** [comment]
Good catch! As I said over on #265: a PR (with tests) would be welcome; otherwise I'll try to get to this in the next week.

**Comment by jgerigmeyer** [comment]
@rjgotten Would you be willing to try against the `master` branch and see if this is adequately fixed? Thanks!
