### ISSUE TITLE
Way to display a subgroup of items together 

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#27]
If we document different sizes of buttons, for instance, they all display with it's own set of code. However, if we want to group all the sized buttons together, there isn't a good way to do this at the moment. 

My ugly workaround went like this:

```
/// Show all regular buttons together, with and without icons
/// Each loop to create brand colors applied with data attribute `data-btn-color`       
/// @group Buttons
/// ... all of my examples ...
[data-btn-size] {
   content: '';
}
```

This was after all of the previously documented [data-btn-size='size'] but had to figure out something quick in order to show them in one area for easier visual comparison.

**Comment by davisagli** [comment]
I've been looking into making it so we can also render doc comments that aren't attached to any Sass. The change proposed in https://github.com/SassDoc/sassdoc/issues/477 would help with this.

**Comment by jgerigmeyer** [comment]
Is this issue still relevant?
