### ISSUE TITLE
Remove uppercase from color names (and everything else)

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#29]
Can't copy and paste it without re-writing.
<img width="869" alt="colors" src="https://cloud.githubusercontent.com/assets/1581694/18411768/7deb1d14-774c-11e6-8c84-a2ec16fd3d68.png">

**Comment by mirisuzanne** [comment]
@stacyk did this already happen? Can we close the issue?

**Comment by stacyk** [comment]
Correct, this is complete
