### ISSUE TITLE
Path to jsonfile not recognized

### ISSUE THREAD

**Issue by bnijenhuis** [oddbird/sassdoc-theme-herman#311]
I have a project where I'm trying to implement Herman, but it does not seem to find the jsonfile I define in the config.json. Other references are used correctly, but the reference to the jsonfile gives the following warning when generating the docs:

[WARNING] File not found: ../assets/css/default/sassdocs.css

The sassdocs.css contains the right generated CSS, and it DOES exist.

My config.json is as follows:

`{
    "theme" : "herman",
    "dest" : "/Library/WebServer/Documents/test_sg/html/styleguide/",
    "package" : "package.json",
    "shortcutIcon" : "../assets/favicon.png",
    "herman" : {
        "customCSS" : "../assets/css/default/total.css",
        "sass" : {
            "jsonfile" : "../assets/css/default/sassdocs.css"
        }
    }
}`

The docs say "Relative path to a sass-json file (created with the herman-export mixin).", but relative to what?

It seems I'm missing something simple, but I can't figure out what. Hope you can help.

**Comment by jgerigmeyer** [comment]
@bnijenhuis The `sass.jsonfile` string should be a path relative to the `cwd` (directory from which you're running sassdoc or the node process).

If you're still having trouble, could you push a stripped-down example repo that I could take a look at?

**Comment by bnijenhuis** [comment]
If I use `../assets/css/default/sassdocs.css`, the error is 

`» [WARNING] File not found: ../assets/css/default/sassdocs.css
ENOENT: no such file or directory, open '../assets/css/default/sassdocs.css'`

But if I use `./assets/css/default/sassdocs.css` the error is:

`» [WARNING] File not found: ./assets/css/default/sassdocs.css
Unexpected token n in JSON at position 27`

Different error on the next line.

**Comment by jgerigmeyer** [comment]
Yeah, the `File not found` message is misleading there... I'll make a note to change that. So it looks like in the second case it is finding your file, but it's not able to read it as valid sass-json. Can you paste the contents of your sassdocs.css file?

http://oddbird.net/herman/docs/api_json-export.html

**Comment by bnijenhuis** [comment]
Okay, at least that's something. Contents of the sassdocs.css file are:

`/*! json-encode: {"fonts": {"sans-stack": {name": "Work Sans, "source": "https://fonts.google.com/specimen/Work+Sans", "stack": [Helvetica Neue, "Lucida Grande"]}}} */`

**Comment by jgerigmeyer** [comment]
Interesting; the `{name":` there is clearly invalid, missing an initial `"`. If you add that manually, does it work? If you regenerate the css file, is it still missing the `"`?

**Comment by bnijenhuis** [comment]
Ok, there were more quotes missing. Not sure why, but manually changing it seems to do the trick. I'll look into the why tomorrow. I will let you know my findings.

**Comment by bnijenhuis** [comment]
Seems Scout-app (which we use for compiling the SCSS) isn't working as it's supposed to. When I generate the CSS using the command line, it's generated as it should and everything works.

Thanks for the help (and maybe add some more documentation regarding the sassjson-file :P )
