### ISSUE TITLE
Basic info missing from docs

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/sassdoc-theme-herman#359]
I'm sorry! It may seen obvious, but... Can't this be added to the installation docs?

``` 
@use '../../node_modules/sassdoc-theme-herman/scss/utilities';
```

Thank you!

**Comment by mirisuzanne** [comment]
Yeah, the details will differ depending on how people install - but that should be in there somewhere.

**Comment by robsonsobral** [comment]
Hi, @mirisuzanne .

Thank you for considering my suggestion!

(It' awesome to contact you again!)
