### ISSUE TITLE
Add tests for assets/ JS and enforce 100% coverage.

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#36]

**Comment by wlonk** [comment]
I'll take a look at this.

**Comment by jgerigmeyer** [comment]
@wlonk Great! As part of this, I'm guessing it would be much easier to test (and just cleaner overall) if we split the huge `index.js` file into multiple files/modules. For instance, `prepareContext` could be its own file, `renderHerman` its own, each annotation its own, etc. I'd be happy to talk through this with you if that'd be helpful.

**Comment by wlonk** [comment]
Yeah, I just discovered the size of it… I think you're right.

Let me take a look at it myself a bit first, then I'll come back around with questions.
