### ISSUE TITLE
`utilities.append()`

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/sassdoc-theme-herman#361]
Hi!

As `utilities.add()` overwrite data, could we have a mixin to merge data and make it easier to use loops to prepare the data?

**Comment by mirisuzanne** [comment]
Now that Sass has a native `map.deep-merge()` function, that's probably the best place to start. We might be able to simply swap that into the `utilities.add()` function, where it handles merging. @robsonsobral do you want to try that, and open a PR?

**Comment by robsonsobral** [comment]
Sure, @mirisuzanne ! I gonna do it ASAP.

**Comment by jgerigmeyer** [comment]
Closed by #365
