### ISSUE TITLE
multiple njk examples break if they require the same import

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#38]
This code breaks:

```
/// @example njk
///   {% import 'static/question/macros.njk' as question %}
///   {{ question.circle() }}
/// @example njk
///   {% import 'static/question/macros.njk' as question %}
///   {{ question.circle(is_accepted=true) }}
/// @example njk
///   {% import 'static/question/macros.njk' as question %}
///   {{ question.circle(is_best=true) }}
```

- It does not work to import once and use it for all three examples
- It does work if you give each import a different name after `as`, which can be used as a temporary workaround

**Comment by davisagli** [comment]
Seems to work for me. *How* does it break for you?

**Comment by mirisuzanne** [comment]
Now I can't recreate. I wonder if it was tied directly to the setup on that project, which has changed now. Closing!
