### ISSUE TITLE
live documentation using this theme ? 

### ISSUE THREAD

**Issue by omarazmi** [oddbird/sassdoc-theme-herman#4]
is there live documentation using this theme, so we can see an example of what done.

**Comment by mirisuzanne** [comment]
All the [accoutrement][http://oddbird.net/accoutrement/] libraries use this theme, and a few of our clients have started to use it (with custom CSS skins) — but the project is very much still incomplete. We're still missing a number of the basic sassdoc features, and some of our own additional features are still incomplete. You're welcome to use it, play around, and contribute — but don't expect a release-ready experience yet!
