### ISSUE TITLE
I want to pass in arbitrary html to the document <head>

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#42]
Especially for use with font CDN's like Typekit, that require an injection script something like:

```
<script src="https://use.typekit.net/unique.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
```

**Comment by davisagli** [comment]
Where would you expect to configure this? When you call sassdoc from webpack or gulp?

**Comment by mirisuzanne** [comment]
@davisagli Yeah, with the other settings. In SassDoc parlance, I think that would usually be a `.sassdocrc` yaml file, but we handle those settings directly through webpack instead. Is that right? I'm not sure if we want the html embedded directly in the settings, or referenced in another file — I'm open to your preference on that.

**Comment by davisagli** [comment]
I think it's simplest to make the option take the actual string to be inserted. The build tool can always load that from a file if that's desired.
