### ISSUE TITLE
Include icons without using nunjucks?

### ISSUE THREAD

**Issue by jgerigmeyer** [oddbird/sassdoc-theme-herman#47]
https://oddbird.slack.com/archives/oddbird/p1484675969000035

**Comment by jgerigmeyer** [comment]
Right now in order to use the `@icons` annotation, we require 5 pieces of information:

1. a path to an `svg` file containing all minified icons in one file (`minifiedIcons`)
2. a `templatepath` or custom `nunjucksEnv`
3. a path to a folder containing `svg` icons
4. a path to a macro file
5. a macro name

That's a lot, and it seems like there isn't really a good reason to require the client to use Nunjucks in order to display a list of SVG icons. Here's a proposal:

We still allow all of those options (with the exception of `minifiedIcons` -- see note below), but *only require #3*. From that, we can pretty easily do everything internally with some defaults: minify the SVGs ourself (and insert them into the iframe `<head>`), create an internal Nunjucks environment, and render a basic default `svg` element with a nested `use` tag for each icon. That would remove the need for Nunjucks entirely, from the client's perspective. (It still only works for SVG icons, but I take it that's sort of the point.)

If we go this route, I think we could also ditch the `minifiedIcons` option entirely, and just replace it with a `customHTML` option that gets inserted into every `@example` iframe, similar to the current `sass.includes` option.

@mirisuzanne @davisagli Thoughts?

**Comment by jgerigmeyer** [comment]
(I'm commenting on this now -- and thinking of promoting it to `Herman 1.0` -- because I think this type of simplification of the API and lowering the barriers to non-Nunjucks tech stacks is directly beneficial to a 1.0 release.)

**Comment by mirisuzanne** [comment]
@jgerigmeyer I agree with everything here. For the icons preview, we're not asking for how you like icons to be used, we're just showing the available SVG files.

For examples, there are two main ways people might use those icons:
- minified in a single sprite sheet, and accessed via `<use>`, like we've generally done.
- individually embedded inline, which likely doesn't require any special support from our end.
