### ISSUE TITLE
Make sure sidebar isn't taking up so much horizontal space.

### ISSUE THREAD

**Issue by SondraE** [oddbird/sassdoc-theme-herman#58]
Related to issue #54 about making the layout full width.

Maybe move to top nav?
Maybe expand collapse? 
- Even a hamburger menu may work since designers and developers will be the ones using the style guide, and they know what the hamburger icon represents.

**Comment by stacyk** [comment]
PR: https://github.com/oddbird/sassdoc-theme-herman/pull/79
