### ISSUE TITLE
I want narrative documentation blocks, not connected to a particular object

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#60]

**Comment by davisagli** [comment]
This depends on https://github.com/SassDoc/sassdoc/issues/477

**Comment by jgerigmeyer** [comment]
Status: waiting on https://github.com/oddbird/sassdoc-theme-herman/pull/140

**Comment by jgerigmeyer** [comment]
Closed by #140.
