### ISSUE TITLE
I want to include documentation from herman-capable npm packages

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#61]
e.g. displaying Accoutrement/Susy documentation inside a project using those tools.

**Comment by davisagli** [comment]
Proposal: add configuration to specify the sass files to include for subprojects:
```
subprojects: {
  'accoutrement-color': 'node_modules/accoutrement-color/sass/*.scss'
}
```

For each subproject, call sassdoc to parse the sassdoc, organize by `@group`, and store in ctx.subprojects. Render a page in a subfolder for each group. And use ctx.subprojects to link to those pages from the sidebar.
