### ISSUE TITLE
Organize color swatches by hue

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#62]
Problem: sometimes we have slightly different colors for things, and we should probably document why that is the case, but it would be nice to be able to filter or display (maybe sort by hue value) color swatches to see the like colors.

Should we collapse all colors that are the same and show them only once (maybe only available in list) with all titles shown that use that color?

**Comment by mirisuzanne** [comment]
We may want to view colors both by hue, and by semantic grouping. That probably means two different display options (one local to a map-group, one displaying all colors).

**Comment by mirisuzanne** [comment]
Identical colors could be combined in the sitewide display

**Comment by wlonk** [comment]
Are we thinking like a toggle, that we can use for "sort semantically" or "sort hue-ily"?
