### ISSUE TITLE
Show sass & css, nunjucks & html beside one another

### ISSUE THREAD

**Issue by stacyk** [oddbird/sassdoc-theme-herman#65]
![screen shot 2017-05-19 at 11 13 12 am](https://cloud.githubusercontent.com/assets/1581694/26263058/f72bd808-3c8b-11e7-9ac9-e6aa29580a81.jpg)

Not necessarily the design I am suggesting, but I think it is helpful to see side by side :)

**Comment by stacyk** [comment]
This would be a tabbed set that includes 2 top level  "Styles" and "Markup"
Styles would include 1-2 panels: `SCSS` and `CSS` if available.
Markup would include 2 panels: `NJK' and 'HTML`

**Comment by jgerigmeyer** [comment]
Closed by #72.
