### ISSUE TITLE
I want to brand Herman.

### ISSUE THREAD

**Issue by SondraE** [oddbird/sassdoc-theme-herman#69]
Maybe use OddBird brand.

**Comment by mirisuzanne** [comment]
Some notes on my goals here:

- Simple/clean look, that can blend with the details of any project/brand using Herman
- Document what small "theming" changes can be made from project to project (logo, accent color, etc)

**Comment by stacyk** [comment]
PR: https://github.com/oddbird/sassdoc-theme-herman/pull/79

**Comment by jgerigmeyer** [comment]
Closed by #79.
