### ISSUE TITLE
How shall we handle styleguide/project CSS conflicts?

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#76]
PR #88, #169

**Comment by jgerigmeyer** [comment]
- [ ] combine `main.css` and `theme.css`; always include
- [ ] `customCSS` should only be available in the `iframe`
- [ ] `minifiedIcons` (`iconsSvg`) should only be available in the `iframe`

**Comment by davisagli** [comment]
- [ ] Add polyfill for `srcdoc` on MS browsers http://caniuse.com/#feat=iframe-srcdoc
- [ ] Set iframe height to fit content (and adjust on resize)

**Comment by mirisuzanne** [comment]
- [ ] output needs label of some sort (or other visual indicator)

**Comment by davisagli** [comment]
There's still at least one thing to work on here (including relative assets from CSS) but it's enough of a step forward and I want to try it out on real projects so I'm going ahead and merging it.

**Comment by jgerigmeyer** [comment]
Proposal:

- fonts appear in iframes, with optional custom headjs
- icons appear in iframes, with custom SVGs
- examples appear in iframes, with custom SVGS, optional custom headjs + optional custom CSS (how are images referenced in CSS handled? what about local font files?)
- fonts pull data from accoutrement-add, possibly including path to a local font file -- we construct the CSS, copying any local font files

**Comment by jgerigmeyer** [comment]
TODO:

- [ ] provide example project using local font files (OddSite temp branch?) _and_ relative paths to images referenced in (documented) SCSS
- [ ] move @preview fonts into iframe with customHead
- [ ] remove customCSS from @icons iframe
- [ ] move customHead into @example iframe
- [ ] make sure @example iframe can access local fonts
- [ ] make sure @example iframe can access webfonts (with customHead as needed)
- [ ] make sure @example iframe can access background-images referenced in customCSS
- [ ] make sure @preview fonts iframe can access local fonts
- [ ] make sure @preview fonts iframe can access webfonts (with customHead as needed)

@mirisuzanne If you're willing to do that first item, I'll start working on the rest.

**Comment by mirisuzanne** [comment]
@jgerigmeyer – https://github.com/oddbird/herman-test-project is up. Once you add sass compilation, export, and herman builds – I can start adding actual samples.

**Comment by jgerigmeyer** [comment]
Ok, I've added the new `@font` annotation, and it works great for remotely-hosted fonts (e.g. typekit and google). Todo:

- [ ] automatically add `@font` custom html to `@example` iframes
- [ ] make sure `@example` iframe can access local fonts
- [ ] make sure `@example` iframe can access background-images referenced in `customCSS`
- [ ] make sure `@font` iframe can access local fonts

**Comment by jgerigmeyer** [comment]
Remaining bugs captured in #174; this is ready for review/merge.
